/**
 * Copyright 2011,2012 National ICT Australia Limited
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.nicta.scoobi.examples

// test.Weather is a class that has been generated by sbt-avro
// based on the schema at: src/main/avro/weather.avsc
import test.Weather

import com.nicta.scoobi.Scoobi._

import edu.berkeley.cs.avro.marker._

object AvroExample extends ScoobiApp {

  def run() {

    // There are WireFormat's for avro records, so there's no problem in creating DLists of them

    val w: DList[Weather] = DList(new Weather("Town Hall", 925, 23), new Weather("Red Fern", 1201, -55), new Weather("Bondi Junction", 1920, 100))

    // and they can easily be persisted, using our schema ( at src/main/avro/weather.avsc )
    persist(toAvroFile(w, "test-output", overwrite = true))

    // and of course, it's easy to read avro files to disk, given a schema!
    val w2: DList[Weather] = fromAvroFile[Weather]("test-output")


    // The other plugin we are using, generates AvroSchema's for case-classes, as we have to do
    // is extend AvroRecord, and make sure all the members are 'var's

    case class Person(var name: String, var awesomeness: Int)
      extends AvroRecord

    implicit val personFmt = mkCaseWireFormat(Person, Person.unapply _)

    val p = new Person("Eric", 10)

    // There are also WireFormat's available, so there's no problem doing all the cool stuff
    // that scoobi allows. e.g.

    val joined: DList[(Person, Weather)] = DObject(p) join w2

    // and let's dump it to a text file, so you can easily verify it worked ;D
    persist(toTextFile(joined, "joined-output", overwrite=true))
  }
}
