/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.nicta.scoobi.testavroschema;  
@SuppressWarnings("all")
@org.apache.avro.specific.FixedSize(20)
@org.apache.avro.specific.AvroGenerated
public class Sha1 extends org.apache.avro.specific.SpecificFixed {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"fixed\",\"name\":\"Sha1\",\"namespace\":\"com.nicta.scoobi.testavroschema\",\"size\":20}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  
  /** Creates a new Sha1 */
  public Sha1() {
    super();
  }
  
  /** Creates a new Sha1 with the given bytes */
  public Sha1(byte[] bytes) {
    super(bytes);
  }
}
